//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_waiter
    {
        public int WaiterID { get; set; }
        public string WaiterName { get; set; }
        public string WaiterContact { get; set; }
        public string WaiterAddress { get; set; }
    }
}
